"""Support Plan / clinician-handoff export.

Renders a Markdown summary of a conversation that the student can save and
optionally bring to a UMD CAPS counselor, ISSS advisor, ADS coordinator, or
graduate Ombuds. The plan is the student's record, never auto-shared.

Sections:

* Header — timestamp, anonymized session id, scope disclaimer
* What I'm working on — paraphrase of the user's first message + later messages
* What I've tried — placeholder; user fills in by hand
* What the navigator surfaced — routes/tiers/recommended action across turns
* Resources mentioned — deduped list with URLs

Tone is plain and stigma-free; never uses clinical labels and never claims to
have diagnosed or treated anything. The deterministic planner already enforces
this; the export simply preserves it.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Iterable


@dataclass
class TurnLogEntry:
    turn_index: int
    timestamp: str
    user_message: str
    route_label: str
    safety_tier: str
    conversation_stage: str
    recommended_action: str
    international_concern: bool
    intl_topic: str
    retrieved_sources: list[dict]


_PRETTY_ROUTE = {
    "academic_setback": "Academic setback",
    "exam_stress": "Exam or test stress",
    "accessibility_ads": "Accessibility / accommodations",
    "advisor_conflict": "Advisor or graduate conflict",
    "counseling_navigation": "Counseling navigation",
    "basic_needs": "Basic needs",
    "care_violence_confidential": "Confidential CARE support",
    "peer_helper": "Helping someone else",
    "loneliness_isolation": "Loneliness or isolation",
    "anxiety_panic": "Anxiety or panic",
    "low_mood": "Low mood",
    "crisis_immediate": "Immediate safety handoff",
    "general_student_support": "General student support",
    "out_of_scope": "Outside support scope",
}


def build_support_plan_markdown(
    turn_log: Iterable[dict | TurnLogEntry],
    started_at: datetime | None = None,
) -> str:
    """Build the Markdown support-plan body.

    Accepts dicts (the demo's session-state shape) or TurnLogEntry objects.
    """
    turns: list[dict] = [_normalize(t) for t in turn_log]
    if not turns:
        return _empty_plan(started_at)

    started = (started_at or datetime.utcnow()).strftime("%Y-%m-%d %H:%M UTC")

    user_msgs = [t["user_message"] for t in turns if t.get("user_message")]
    routes = _dedupe_in_order([t["route_label"] for t in turns if t.get("route_label")])
    intl_topics = _dedupe_in_order([t["intl_topic"] for t in turns if t.get("intl_topic")])
    actions = _dedupe_in_order([t["recommended_action"] for t in turns if t.get("recommended_action")])
    resources = _dedupe_resources(turns)

    lines: list[str] = []
    lines.append("# Support plan")
    lines.append("")
    lines.append(f"_Generated by EmpathRAG, a UMD support-navigation prototype._")
    lines.append(f"_Created: {started}._")
    lines.append("")
    lines.append("> This is your record. EmpathRAG is not therapy, diagnosis, or emergency care.")
    lines.append("> The navigator only points to UMD resources; it does not interpret policy on your behalf.")
    lines.append("")

    lines.append("## What I'm working on")
    lines.append("")
    if user_msgs:
        lines.append("In my own words:")
        lines.append("")
        for m in user_msgs:
            lines.append(f"- {m.strip()}")
    else:
        lines.append("_No messages recorded yet._")
    lines.append("")

    lines.append("## What I've tried")
    lines.append("")
    lines.append("- _Fill in by hand: things I've already attempted, who I've already talked to, what helped or didn't._")
    lines.append("")

    lines.append("## What the navigator surfaced")
    lines.append("")
    if routes:
        pretty = ", ".join(_PRETTY_ROUTE.get(r, r.replace("_", " ").title()) for r in routes)
        lines.append(f"- Topics identified: {pretty}")
    if intl_topics:
        pretty = ", ".join(t.replace("_", " ") for t in intl_topics)
        lines.append(f"- F-1 / international sub-topics: {pretty}")
    if actions:
        lines.append("- Suggested next steps:")
        for a in actions:
            lines.append(f"  - {a.strip().rstrip('.')}")
    lines.append("")

    lines.append("## Resources mentioned")
    lines.append("")
    if resources:
        for r in resources:
            line = f"- **{r['source_name']}**"
            if r.get("title"):
                line += f" — {r['title']}"
            if r.get("url") and r["url"] not in {"", "N/A"}:
                line += f" ({r['url']})"
            lines.append(line)
    else:
        lines.append("_None surfaced yet — keep talking to see relevant resources._")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_If you bring this to a counselor or ISSS advisor: feel free to paste their notes below._")
    lines.append("")
    return "\n".join(lines)


def _empty_plan(started_at: datetime | None) -> str:
    started = (started_at or datetime.utcnow()).strftime("%Y-%m-%d %H:%M UTC")
    return (
        "# Support plan\n\n"
        f"_Generated: {started}._\n\n"
        "_No conversation yet. Send a message first, then download._\n"
    )


def _normalize(t: dict | TurnLogEntry) -> dict:
    if isinstance(t, TurnLogEntry):
        return {
            "turn_index": t.turn_index,
            "timestamp": t.timestamp,
            "user_message": t.user_message,
            "route_label": t.route_label,
            "safety_tier": t.safety_tier,
            "conversation_stage": t.conversation_stage,
            "recommended_action": t.recommended_action,
            "international_concern": t.international_concern,
            "intl_topic": t.intl_topic,
            "retrieved_sources": t.retrieved_sources,
        }
    return dict(t)


def _dedupe_in_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for x in items:
        if not x:
            continue
        if x in seen:
            continue
        seen.add(x)
        out.append(x)
    return out


def _dedupe_resources(turns: list[dict]) -> list[dict]:
    """Collapse retrieved_sources across turns by (source_name, title)."""
    seen: set[tuple[str, str]] = set()
    out: list[dict] = []
    for t in turns:
        for r in t.get("retrieved_sources", []) or []:
            key = (r.get("source_name", ""), r.get("title", ""))
            if not key[0]:
                continue
            if key in seen:
                continue
            seen.add(key)
            out.append(r)
    return out
